/*
  dados.js
  Grade curricular - Pedagogia Integral - UNICAMP (curso 20G)
  Fonte: Catálogo de Graduação UNICAMP 2026 (dac.unicamp.br), currículo
  sugerido do curso 20G - Pedagogia ("Proposta para Cumprimento de Currículo")
  e ementas oficiais de cada disciplina (Comissão de Graduação dos Cursos de
  Pedagogia).

  SOBRE OS PRÉ-REQUISITOS:
  A grade oficial de Pedagogia tem pouquíssimos pré-requisitos entre
  disciplinas — a maioria pode ser cursada em qualquer ordem dentro do
  semestre sugerido. Os poucos pré-requisitos que o catálogo lista são, na
  maior parte, regras institucionais genéricas (ex: "AA430" = número mínimo
  de créditos já integralizados), que não apontam para uma disciplina
  específica e por isso não entram na cadeia de "desbloqueio" visual do
  planejador. A única cadeia real entre disciplinas é EP808 → EP809 (TCC I
  antes do TCC II). Ajuste livremente aqui caso sua turma tenha um currículo
  diferente.

  SOBRE OS CRÉDITOS ELETIVOS:
  Os 4º, 6º e 7º semestres também incluem créditos eletivos de livre escolha
  (4 créditos cada), representados como um item "Créditos Eletivos" — igual
  ao modelo usado no planejador de Engenharia Mecânica.
*/

const DISCIPLINAS = [
  // ---------- 1º SEMESTRE ----------
  { codigo: "EP107", nome: "Introdução à Pedagogia - Organização do Trabalho Pedagógico", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "O objetivo das ciências da educação. O problema da unidade, especificidade e autonomia das ciências da educação. A educação como ponto de partida e de chegada dos estudos e das reflexões dos cientistas. A contribuição das ciências para a explicação e compreensão da educação. Contextualização histórica da Pedagogia no Brasil - o curso de Pedagogia da Unicamp." },
  { codigo: "EP110", nome: "História da Educação I", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Introdução à História da Educação. Bases epistemológicas, metodológicas e teóricas da História e História da Educação. Fundamentos da História e História da Educação e da pedagogia: na antiguidade, na medievalidade, na modernidade e na contemporaneidade geral e no Brasil." },
  { codigo: "EP130", nome: "Filosofia da Educação I", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Introdução à filosofia mediante sua caracterização em face de outras formas de conhecimento. Estudo de pensadores antigos que contribuíram significativamente para a reflexão sobre problemas pedagógicos ou que forneceram os fundamentos filosóficos da educação ocidental, entre eles: Sócrates, os sofistas, Platão e Aristóteles." },
  { codigo: "EP140", nome: "Sociologia Geral", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Analisa as principais teorias sociológicas que procuram indagar e explicar a sociedade moderna e as mudanças observadas na sociedade contemporânea. Introduz categorias analíticas que informam e expressam o pensamento de seus fundadores Karl Marx, Émile Durkheim e Max Weber, autores considerados clássicos em sociologia porque participaram da construção deste campo científico, por meio de  interpretações e visões de mundo diversas, frequentemente antagônicas. Discute questões sociais observadas no presente à luz das teorias analisadas." },
  { codigo: "EP142", nome: "Educação e Antropologia Cultural", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Ao propor um diálogo entre educação e antropologia, a disciplina visa discutir a pertinência desta área do conhecimento para a atividade pedagógica como expressão de culturas específicas e de processos históricos e sociais determinados. Os objetivos específicos do curso são introduzir os alunos no quadro conceitual e temático da antropologia, discutir alguns expoentes da literatura antropológica sobre ciclos de vida (especialmente sobre infância e juventude), diversidade cultural, multiculturalismo e interculturalidade na sociedade contemporânea e, em particular, na escola; por fim, pretende-se mostrar a especificidade da antropologia que reside no modo pelo qual delimita seus campos de estudo, propondo modelos de interpretação e análise." },
  { codigo: "EP570", nome: "Estudo e Produção Acadêmica", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Textos acadêmico-científicos da área educacional, suas características e especificidades. Modalidades de textos científicos. Reflexão e prática de leitura e produção de textos acadêmicos nas diversas modalidades. Dimensões metodológicas, técnicas e éticas da escrita, envolvendo o letramento acadêmico." },

  // ---------- 2º SEMESTRE ----------
  { codigo: "EP128", nome: "Psicologia I", semestre: 2, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Contribuições das perspectivas teóricas comportamental, social cognitiva e psicanalítica para o estudo do processo de ensino, aprendizagem e desenvolvimento e suas aplicações para o contexto educativo." },
  { codigo: "EP210", nome: "História da Educação II", semestre: 2, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "História Moderna e História da Educação no Brasil no período colonial e no Império." },
  { codigo: "EP230", nome: "Filosofia da Educação II", semestre: 2, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Estudo dos filósofos e/ou correntes filosóficas medievais e modernas que mais significativamente contribuíram para a reflexão sobre problemas pedagógicos ou que forneceram os fundamentos filosóficos da educação ocidental: a patrística, a escolástica, o racionalismo, o empirismo e a concepção educacional de Rousseau." },
  { codigo: "EP340", nome: "Sociologia da Educação I", semestre: 2, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Introduz os estudantes aos temas da Sociologia da Educação por intermédio de abordagem de autores clássicos - Karl Marx, Max Weber e Émile Durkheim - e dos seus novos enfoques. Propicia a compreensão das dimensões sociais da Educação, na sociedade contemporânea, a partir de categorias analíticas das principais teorias sociológicas. Analisa a relevância da educação nas relações sociais que engendram exploração, dominação e solidariedade." },
  { codigo: "EP347", nome: "Educação, Cultura e Linguagens", semestre: 2, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Estudos sobre as diferentes linguagens verbais (fala e escrita), visuais (artes plásticas) e audiovisuais (cinema e televisão) que dão forma à Educação cultural e escolar,ao imaginário e à inteligência contemporâneas." },
  { codigo: "EP381", nome: "Pesquisa, Prática pedagógica e de extensão", semestre: 2, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Esta disciplina tem por objetivo aproximar o estudante do campo profissional da pedagogia. Para tanto, pautar-se-á pela apresentação da produção acadêmico-científica das linhas de pesquisa da FE e seus diálogos com a prática desse profissional. Pretende-se, desta forma, ampliar a perspectiva do estudante sobre a diversidade teórica, metodologia e de extensão, que subsidia a pesquisa educacional e contribuir para a compreensão da prática pedagógica em uma perspectiva diversificada." },

  // ---------- 3º SEMESTRE ----------
  { codigo: "EP129", nome: "Psicologia II", semestre: 3, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Contribuições das perspectivas teóricas construtivista e histórico-cultural para o estudo do processo de ensino, aprendizagem e desenvolvimento e suas implicações para o contexto educativo." },
  { codigo: "EP152", nome: "Didática - Teoria Pedagógica", semestre: 3, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "As características da instituição escolar no contexto socioeconômico cultural brasileiro: objetivos, finalidades, organização, política educacional, recursos humanos e materiais. As diferentes formas de ensino como planos de organização e processos de interação. Identificação e análise de estratégias de ensino, da natureza dos conteúdos e das formas de avaliação em consonância com as características da clientela escolar." },
  { codigo: "EP165", nome: "Política Educacional: Organização da Educação Brasileira", semestre: 3, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Estudo analítico das políticas educacionais no Brasil com destaque para: a política educacional no contexto das políticas públicas; organizações dos sistemas de ensino considerando as peculiaridades nacionais e os contextos internacionais; políticas educacionais e legislação de ensino, organização da educação básica e do ensino superior; impasses e perspectivas das políticas atuais em relação à educação." },
  { codigo: "EP330", nome: "Filosofia da Educação III", semestre: 3, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Estudo de filósofos e/ou correntes filosóficas contemporâneas que mais significativamente contribuíram para a reflexão sobre problemas pedagógicos ou que forneceram fundamentos filosóficos da educação ocidental, iniciando com o iluminismo kantiano incluindo as concepções positivista , pragmatista, marxista, entre outras." },
  { codigo: "EP412", nome: "História da Educação III", semestre: 3, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "História e História da Educação e da Escola no mundo contemporâneo e no Brasil republicano. Problemas e perspectivas da Educação contemporânea no Brasil e no mundo globalizado." },

  // ---------- 4º SEMESTRE ----------
  { codigo: "EP153", nome: "Metodologia do Ensino Fundamental", semestre: 4, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Trabalho de campo orientado para o diagnóstico dos componentes metodológicos envolvidos na prática educativa das escolas públicas de ensino fundamental, procurando analisá-las no conjunto das determinações mais amplas a que estão submetidas. Numa perspectiva integrada da área de Magistério, propor reflexões a partir da prática das escolas, a serem encaminhadas para as metodologias específicas, visando a continuidade do trabalho." },
  { codigo: "EP158", nome: "Educação, Corpo e Arte", semestre: 4, creditos: 8, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Esta disciplina, de caráter teórico-prático, objetiva introduzir o (a) aluno (a) em diferentes linguagens corporais e/ou artísticas nas suas relações com o processo educacional, tanto no âmbito da instituição escolar (com ênfase na Educação Infantil e séries iniciais do Ensino Fundamental), como no contexto de outros espaços educativos." },
  { codigo: "EP164", nome: "Organização do Trabalho Pedagógico e Gestão Escolar", semestre: 4, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Fundamentos teóricos da Administração. Teorias da Administração e Gestão Educacional. Escola, Gestão e Projeto Político da escola. A organização do trabalho escolar: linguagem, tempo, espaço." },
  { codigo: "EP226", nome: "Psicologia e Educação", semestre: 4, creditos: 5, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Análise de questões relativas ao contexto educativo fundamentada na Psicologia, com base em pesquisas científicas e práticas de extensão universitária." },
  { codigo: "EP372", nome: "Avaliação", semestre: 4, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "A disciplina toma a escola como objeto de estudo, do ponto de vista de sua organização do trabalho pedagógico; insere a avaliação nesse contexto e discute a função ideológica da escola e dos processos de avaliação. São examinados os vários níveis de avaliação - em sala de aula, institucional e de redes de ensino. Discutem-se novas abordagens para o trabalho pedagógico que permitam visualizar novas formas de avaliação." },
  { codigo: "EP445", nome: "Sociologia da Educação II", semestre: 4, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Propicia aos estudantes uma reflexão das preocupações e produções no âmbito da Sociologia da Educação, com ênfase na educação escolar, em diálogo com os processos sociais, políticos e econômicos internacionais na sociedade contemporânea. Contribui para o conhecimento sociológico das diferentes visões que se manifestam e se confrontam nas políticas públicas de educação na atualidade." },
  { codigo: "ELET-4S", nome: "Créditos Eletivos (4º sem.)", semestre: 4, creditos: 4, tipo: "Eletiva", departamento: "Livre escolha", prerequisitos: [], ementa: "Disciplina eletiva de livre escolha do(a) aluno(a) — não possui ementa fixa, pois depende da disciplina escolhida a cada semestre.", eletivaPlaceholder: true },

  // ---------- 5º SEMESTRE ----------
  { codigo: "EP376", nome: "Práticas de Ensino e Estágio Supervisionado nos Anos Iniciais do Ensino Fundamental", semestre: 5, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Planejamento, desenvolvimento e avaliação dos projetos de ensino envolvidos nas práticas educativas dos anos iniciais do Ensino Fundamental. Constitui espaço para tratamento interdisciplinar dos fundamentos oferecidos." },
  { codigo: "EP471", nome: "Escola, Alfabetização e Culturas da Escrita", semestre: 5, creditos: 8, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Conhecimentos da ordem da escrita, seus usos e objetos, discursos e lugares de produção, circulação, divulgação. Estudos sobre linguagem e ensino da Língua Portuguesa: práticas orais, de leitura, de escrita, de análise linguística. Alfabetização e Letramento: conceitos e práticas ligadas à cultura da escrita." },
  { codigo: "EP472", nome: "Escola e Conhecimento de História e Geografia", semestre: 5, creditos: 8, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Estudos sobre as questões de tempo e de espaço, como produções socioculturais, inscritas nas culturas escolares. Essas questões serão aprofundadas levando-se  em conta os conteúdos das séries iniciais." },
  { codigo: "EP473", nome: "Escola e Cultura Matemática", semestre: 5, creditos: 8, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Identificar, caracterizar e problematizar, de forma multidisciplinar e comparativa, os condicionamentos singulares que conformam as práticas escolares e não escolares que envolvam cultura matemática, visando a formação reflexiva e crítica do professor para o ensino dos conteúdos curriculares de Matemática do Ensino Fundamental I e da Educação Infantil. Relações com os diferentes contextos onde os professores podem desenvolver sua prática profissional, quer sejam contextos de educação formal, não-formal ou informal." },
  { codigo: "EP474", nome: "Escola e Conhecimento em Ciências Naturais", semestre: 5, creditos: 8, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Movimentos históricos do Ensino de Ciências no Brasil. Aspectos teóricos e metodológicos do ensino de Ciências: atividades práticas, resolução de problemas, concepções prévias, estudos do meio, abordagem interdisciplinar, recursos e materiais didáticos. Diretrizes curriculares de Ciências para o Ensino Fundamental e Educação Infantil. Linguagens no ensino de Ciências. Relações Ciência, Tecnologia, Sociedade e Ambiente. Produção e divulgação do conhecimento científico. Alfabetização científica e currículo escolar. Temas e conhecimentos escolares no ensino de Ciências. Relações com os diferentes contextos onde os professores podem desenvolver sua prática profissional, quer sejam contextos de educação formal, não-formal ou informal." },
  { codigo: "EP910", nome: "Estágio Supervisionado I - Gestão Escolar", semestre: 5, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Acompanhamento do processo de organização e administração da escola (educação básica e suas modalidades) enquanto unidade vinculada a um sistema de ensino, buscando o entendimento de seus problemas cotidianos e alternativas de solução baseadas nos fundamentos da política e da administração educacional." },

  // ---------- 6º SEMESTRE ----------
  { codigo: "EP144", nome: "Metodologia da Pesquisa em Ciências da Educação I", semestre: 6, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "A disciplina visa inserir os estudantes de Pedagogia no exercício da pesquisa em Ciências Sociais e Educação, focalizando aspectos relacionados às dimensões teórico-metodológicas, às etapas básicas da pesquisa e a elaboração do projeto de pesquisa, bem como o delineamento dos procedimentos para a descrição, análise e interpretação da realidade social e educacional." },
  { codigo: "EP377", nome: "Planejamento Educacional e Estágio Supervisionado em Gestão Escolar", semestre: 6, creditos: 8, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Acompanhamento e análise do processo de planejamento escolar e educacional no âmbito da educação básica e suas modalidades, como fase decisiva da implementação da política e da administração da educação, levando em conta os fundamentos teóricos que embasam a organização da escola e do sistema educacional." },
  { codigo: "EP790", nome: "Políticas de Educação Infantil", semestre: 6, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Descrição e análise dos fundamentos históricos, políticos, econômicos e sociais na Educação Infantil. Conceito de infância, de família e suas historicidades. Funções da Educação Infantil. Políticas de atendimento à infância. Creche e pré-escola.Relação Educação Infantil e Ensino Fundamental." },
  { codigo: "EP911", nome: "Estágio Supervisionado II - Anos Iniciais do Ensino Fundamental", semestre: 6, creditos: 8, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Estágio junto às escolas de educação fundamental (anos iniciais), direcionado ao trabalho pedagógico, entendido na articulação entre a docência e a gestão escolar, observação e análise da sala de aula e sua articulação com os demais espaços da escola." },
  { codigo: "ELET-6S", nome: "Créditos Eletivos (6º sem.)", semestre: 6, creditos: 4, tipo: "Eletiva", departamento: "Livre escolha", prerequisitos: [], ementa: "Disciplina eletiva de livre escolha do(a) aluno(a) — não possui ementa fixa, pois depende da disciplina escolhida a cada semestre.", eletivaPlaceholder: true },

  // ---------- 7º SEMESTRE ----------
  { codigo: "EP139", nome: "Pedagogia da Educação Infantil", semestre: 7, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Esta disciplina discute o conceito de infância a partir das contribuições das Ciências Sociais. Traça um breve histórico da Educação infantil e do desenvolvimento dos Estudos da Infância no Brasil.  A partir da articulação com os documentos do MEC para a Educação Infantil e da produção atual de pesquisadoras/es da infância e da educação infantil, propõe-se o estudo da(s) pedagogia(s) da educação infantil tendo como principais eixos de discussão: o currículo, a ação docente, o papel das culturas infantis, da arte e das múltiplas linguagens nos processos de educação e socialização de bebês e crianças e o lugar da diferença (sobretudo de gênero e raça/etnia) em creches e pré-escolas." },
  { codigo: "EP146", nome: "Educação e Tecnologias", semestre: 7, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Abordagem interdisciplinar, propondo-se o tratamento das tecnologias de comunicação e informação no ambiente educativo. Os alunos vivenciarão situações práticas que os levarão a refletir criticamente sobre o uso de tecnologias na educação." },
  { codigo: "EP162", nome: "Escola e Currículo", semestre: 7, creditos: 5, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "História do Currículo, concepções de currículo, fundamentos filosóficos, sociológicos, históricos e culturais, teorias e práticas curriculares. Análise e compreensão da transformação do conhecimento, da educação e da escola na contemporaneidade." },
  { codigo: "EP282", nome: "Práticas extracurriculares de extensão", semestre: 7, creditos: 2, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Estudante deverá desenvolver atividades de extensão" },
  { codigo: "EP348", nome: "Educação Especial e Inclusão", semestre: 7, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "O acesso ao conhecimento e aos ambientes sociais e escolares de alunos com deficiência e altas habilidades, diante da responsabilidade de se garantir o direito à educação, como prescrição constitucional, no ensino básico e superior. A produção social da normalidade e da anormalidade. A constituição da educação especial e as propostas de escolarização das pessoas com deficiência, em diferentes momentos históricos. Relações com os diferentes contextos onde os professores podem desenvolver sua prática profissional, quer sejam contextos onde os professores podem desenvolver sua prática profissional, quer sejam contextos de educação formal, não-formal ou informal." },
  { codigo: "EP808", nome: "Trabalho de Conclusão de Curso I", semestre: 7, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "O aluno deverá iniciar trabalho de conclusão de curso, nos termos da deliberação da Congregação da FE, o qual será desenvolvido sob orientação de um docente da FE." },
  { codigo: "EP912", nome: "Estágio Supervisionado III - Educação Infantil", semestre: 7, creditos: 8, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Estágio em Instituições Formais de Educação da 1ª etapa da educação básica: creches e pré-escolas. Observação da (des)organização do tempo e do espaço físico. Observação da relação criança-criança e da construção das culturas infantis. Observação da relação adulto (professoras/es, educadoras/es)-criança e as condições de produção das culturas infantis. Observação da relação adulto-adulto entre eles/as, hierarquia de poder, gestão e co-gestão (pais, mães, responsáveis pelas crianças, professoras/es e educadoras/es, orientadoras/es, supervisoras/es, diretoras/es, vice-diretoras/es, coordenadoras/es)." },
  { codigo: "ELET-7S", nome: "Créditos Eletivos (7º sem.)", semestre: 7, creditos: 4, tipo: "Eletiva", departamento: "Livre escolha", prerequisitos: [], ementa: "Disciplina eletiva de livre escolha do(a) aluno(a) — não possui ementa fixa, pois depende da disciplina escolhida a cada semestre.", eletivaPlaceholder: true },

  // ---------- 8º SEMESTRE ----------
  { codigo: "EP529", nome: "Educação de Surdos e Língua de Sinais", semestre: 8, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Conhecimentos teórico-práticos introdutórios de Libras, assumindo-a como elemento constitutivo do conhecimento do aluno sobre a surdez. Estudo sobre os parâmetros que caracterizam a Libras como língua; relação língua e constituição do sujeito humano; história da educação e as organizações dos movimentos políticos dos surdos; comunidades surdas e suas produções culturais; abordagens pedagógicas no ensino da pessoa surda; projetos de educação bilíngue." },
  { codigo: "EP809", nome: "Trabalho de Conclusão de Curso II", semestre: 8, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: ["EP808"], ementa: "O aluno deverá apresentar trabalho de conclusão de curso sob orientação de um docente da FE, nos termos da deliberação da Congregação da FE." },
  { codigo: "EP879", nome: "Educação de Jovens e Adultos", semestre: 8, creditos: 3, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Reflexões sobre a perspectiva histórica do direito à Educação para jovens e adultos: direitos, concepções e funções sociais. Abordagem da Educação de Jovens e Adultos enquanto campo de direitos e suas singularidades. As políticas educacionais para Educação de Jovens e Adultos. Cursos ofertados nos diferentes níveis de ensino (Fundamental e Médio) e articulação com a Educação Profissional. Projetos e experiências desenvolvidos na proposta para a modalidade EJA." },
  { codigo: "EP887", nome: "Educação Não Formal", semestre: 8, creditos: 6, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "A disciplina objetiva fornecer aos alunos uma visão teórico-prática sobre modos, formas e processos educacionais existentes na sociedade e que possa contribuir para a formação crítica do profissional da área da Educação, especialmente em campos que dizem respeito à formação para a cidadania do indivíduo e à atuação de grupos socioculturais." },
  { codigo: "EP914", nome: "Estágio Supervisionado V - Educação Não Formal", semestre: 8, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Fornecer conhecimento teórico-prático para uma melhor compreensão da educação não-formal, permitindo que os alunos: 1- percebam, que o campo de trabalho do pedagogo é mais amplo do que o da escola formal; 2 - se conscientizem de que a educação não formal tem propósitos: a) reformadores, contribuindo para o melhor funcionamento da sociedade, b) transformadores objetivando formar nos educandos uma atitude frente à realidade, que busque a transformação social, c) mesclando as duas atitudes ao realizar a educação; 3 - conhecendo propostas não-formais de caráter transformador." },
  { codigo: "EP915", nome: "Histórias e Culturas Afro-brasileiras e Africanas", semestre: 8, creditos: 3, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Ideologia da democracia racial, relações racializadas no Brasil e o papel da escola – aspectos históricos e contemporâneos; educação das relações étnico-raciais; ações afirmativas e perspectivas (políticas, institucionais e relacionais) de enfrentamento ao racismo; africanidades em práticas culturais e educativas." },
  { codigo: "EP916", nome: "Histórias e Culturas de Povos Indígenas Brasileiros", semestre: 8, creditos: 3, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Estudos sobre as dinâmicas culturais dos povos indígenas no Brasil. Processos históricos e sociais de contato com as sociedades não- indígenas. Saberes, práticas culturais e educativas indígenas." },
  { codigo: "EP923", nome: "Prática e Extensão em Educação Infantil", semestre: 8, creditos: 4, tipo: "Obrigatória", departamento: "Pedagogia (FE)", prerequisitos: [], ementa: "Prática e Extensão em Educação Infantil Pública (creches e pré-escolas), a partir da participação no cotidiano da instituição, observação, escuta e interação com bebês, crianças, e adultos da comunidade educacional/ou das famílias. Articulação das vivências com temas contemporâneos e de interesse social." },

];

// Total de créditos do currículo (usado no dashboard)
const TOTAL_CREDITOS_CURSO = DISCIPLINAS.reduce((soma, d) => soma + d.creditos, 0);
const TOTAL_DISCIPLINAS_CURSO = DISCIPLINAS.length;
const NOME_CURSO = "Pedagogia Integral";
const INSTITUICAO = "UNICAMP";
const NUM_SEMESTRES = 8;