/*
  dados.js
  Grade curricular - Engenharia Mecânica - UNICAMP (curso 10G)
  Fonte dos códigos, nomes e créditos: Catálogo de Graduação UNICAMP 2025/2026
  (proposta de currículo do curso 10G) e Matriz Curricular da FEM.

  IMPORTANTE SOBRE OS PRÉ-REQUISITOS:
  A lista oficial de pré-requisito por pré-requisito não estava disponível
  para leitura automática (o catálogo da DAC bloqueia acesso automatizado).
  Os pré-requisitos abaixo foram inferidos a partir da ordem sugerida do
  currículo e do encadeamento típico dessas disciplinas (ex: Cálculo I antes
  de Cálculo II, Estática antes de Dinâmica, etc). Confira e ajuste livremente
  aqui no arquivo dados.js caso encontre alguma diferença em relação à grade
  oficial da sua turma/currículo.

  SOBRE O CAMPO "ementa":
  As ementas foram obtidas automaticamente a partir do Catálogo de Graduação
  da UNICAMP (dac.unicamp.br) para as disciplinas da FEM, IMECC e IFGW, e por
  meio de busca complementar para disciplinas de outros institutos (IQ, IC,
  FEEC, IB, IE). O código "EM104" da grade não corresponde, no catálogo atual,
  à disciplina "Materiais Poliméricos" (o catálogo lista esse nome sob o código
  "EM014"); por segurança, a ementa desse item foi deixada em aberto — confira
  o código correto junto à sua Comissão de Graduação e ajuste manualmente.
*/

const DISCIPLINAS = [
  // ---------- 1º SEMESTRE ----------
  { codigo: "EM102", nome: "Desenho Técnico", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: [], ementa: "Instrumentação, normas, convenções e padronização. Fase do desenho (croquís, desenho preliminar). Cotagem. Perspectivas. Sistemas de projeções. Vistas principais parciais e auxiliares. Cortes e seções. Indicações de tolerância e ajustes. Desenhos de elementos de máquinas. Elementos de união (soldas, parafusos, rebites). Conjunto montado." },
  { codigo: "EM110", nome: "Introdução à Engenharia Mecânica", semestre: 1, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: [], ementa: "Noções gerais sobre ciência e tecnologia. Fundamentos metodológicos de engenharia. Origem e evolução da engenharia mecânica. A engenharia mecânica brasileira. A Faculdade de Engenharia Mecânica da Unicamp. Atribuições profissionais e perspectiva do mercado do trabalho." },
  { codigo: "EM120", nome: "Introdução à Prática de Extensão em Engenharia", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: [], ementa: "História da Universidade Brasileira: Ensino, Pesquisa e Extensão Universitária. Conceito de extensão universitária. Concepções e Tendências da Extensão Universitária. Importância acadêmica e social da Extensão Universitária. Legislação da Extensão Universitária. Procedimentos Metodológicos, Didáticos e Técnico-Científicos. Etapas para a Elaboração de Atividades e Projetos de Extensão Universitária. Desenvolvimento de atividades de extensão." },
  { codigo: "F 128", nome: "Física Geral I", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Física (IFGW)", prerequisitos: [], ementa: "Cinemática do ponto. Leis de Newton. Estática e dinâmica da partícula. Trabalho e energia. Conservação da Energia. Momento linear e sua conservação. Colisões. Momento angular da partícula e de sistemas de partículas. Rotação de corpos rígidos." },
  { codigo: "MA111", nome: "Cálculo I", semestre: 1, creditos: 6, tipo: "Obrigatória", departamento: "Matemática (IMECC)", prerequisitos: [], ementa: "Intervalos e desigualdades. Funções. Limites. Continuidade. Derivada e diferencial. Integral. Técnicas de integração." },
  { codigo: "MA141", nome: "Geometria Analítica e Vetores", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Matemática (IMECC)", prerequisitos: [], ementa: "Sistemas lineares. Vetores, operações. Bases, sistemas de coordenadas. Distância, norma e ângulo. Produtos escalar e vetorial. Retas no plano e no espaço. Planos. Posições relativas, interseções, distâncias e ângulos. Círculo e esfera. Coordenadas polares, cilíndricas e esféricas. Seções cônicas, classificação. Introdução às quádricas." },
  { codigo: "QG101", nome: "Química Geral", semestre: 1, creditos: 4, tipo: "Obrigatória", departamento: "Química (IQ)", prerequisitos: [], ementa: "Estrutura atômica, classificação periódica e propriedades dos elementos. Ligação química; estrutura e propriedades das substâncias. Noções de físico-química: termodinâmica, equilíbrios químicos e células eletroquímicas." },

  // ---------- 2º SEMESTRE ----------
  { codigo: "EM103", nome: "Metodologia de Pesquisa e Redação Científica", semestre: 2, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: [], ementa: "Condução de revisão bibliográfica. Estruturas de trabalhos, relatórios, dissertações e teses. Normas de orientação bibliográfica e normas de apresentação de trabalhos. Estrutura e orientação para a formulação de artigos e resumo." },
  { codigo: "EM200", nome: "Desenho Assistido por Computador", semestre: 2, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM102"], ementa: "Introdução a um programa computacional de desenho. Desenhos de elementos de máquinas (sistemas de transmissão, mancais, conexões, etc.). Desenhos de conjunto. Detalhamento de conjunto." },
  { codigo: "EM240", nome: "Estrutura e Propriedades dos Materiais", semestre: 2, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["QG101"], ementa: "Estrutura e defeitos cristalinos. Difusão atômica. Soluções sólidas. Nucleação e Crescimento de fases. Diagramas de fase. Recuperação, recristalização e crescimento de grãos. Solubilização e Precipitação." },
  { codigo: "EM306", nome: "Estática", semestre: 2, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["F 128", "MA141"], ementa: "Sistemas de forças aplicadas equivalentes. Equilíbrio de um corpo rígido. Equilíbrio de corpos rígidos interligados. Treliças planas e espaciais. Baricentro e carregamento distribuído. Esforços internos em elementos estruturais. Diagrama dos esforços solicitantes. Momento de inércia de figuras planas. Atrito" },
  { codigo: "F 159", nome: "Introdução à Física Experimental I", semestre: 2, creditos: 2, tipo: "Obrigatória", departamento: "Física (IFGW)", prerequisitos: ["F 128"], ementa: "Distribuições de probabilidade; Avaliação e expressão de incertezas; Algarismos significativos; Uso de instrumentos de medição de dimensões físicas e grandezas eletromagnéticas; Variáveis dependente e independente; Organização de dados em tabelas; Confecção e análise de gráficos e histogramas; Medições diretas e indiretas; Propagação de incertezas; Comparação de medidas experimentais distintas; Ajuste de curvas e leis de escalas; Modelos, suposições e limites de validade; Trabalho em equipe e ética científica." },
  { codigo: "F 328", nome: "Física Geral III", semestre: 2, creditos: 4, tipo: "Obrigatória", departamento: "Física (IFGW)", prerequisitos: ["F 128"], ementa: "Lei de Coulomb, Campo Elétrico, Lei de Gauss, Potencial Elétrico, Capacitância, Corrente e Resistência, Força Eletromotriz e Circuitos Elétricos, Campo Magnético, Lei de Ampère, Lei da Indução de Faraday, Indutância, Propriedades Magnéticas da Matéria, Oscilações Eletromagnéticas, Correntes Alternadas, Equações de Maxwell. Obs.: Recomenda-se que seja cursada previamente MA251 ou disciplina equivalente." },
  { codigo: "MA211", nome: "Cálculo II", semestre: 2, creditos: 6, tipo: "Obrigatória", departamento: "Matemática (IMECC)", prerequisitos: ["MA111"], ementa: "Funções de várias variáveis reais. Fórmula de Taylor. Máximos e mínimos. Integrais múltiplas. Integrais de linha. Teorema da divergência. Teorema de Stokes." },
  { codigo: "ME414", nome: "Estatística para Experimentalistas", semestre: 2, creditos: 4, tipo: "Obrigatória", departamento: "Estatística (IMECC)", prerequisitos: ["MA111"], ementa: "Conceitos básicos de probabilidade e estatística descritiva. Principais distribuições discretas e contínuas: Binomial, Hipergeométrica, Poisson, Normal, t, F, qui-quadrado. Amostragem. Estimação, teste de hipótese e intervalo de confiança para médias, proporções e variâncias. Regressão e correlação. Análise de variância." },
  { codigo: "ELET-2S", nome: "Créditos Eletivos (2º sem.)", semestre: 2, creditos: 2, tipo: "Eletiva", departamento: "Livre escolha", prerequisitos: [], ementa: "Disciplina eletiva de livre escolha do(a) aluno(a) — não possui ementa fixa, pois depende da disciplina escolhida a cada semestre.", eletivaPlaceholder: true },

  // ---------- 3º SEMESTRE ----------
  { codigo: "EM330", nome: "Oficinas I", semestre: 3, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM102"], ementa: "Medidas lineares com instrumentos de medida direta e indireta. Noções de tolerância ISO. Traçagem de peças, trabalhos de bancada. Operações básicas com máquinas operatrizes, furadeira, plaina limadora, torno mecânico horizontal e fresadora. Obs.: Realizado nas oficinas da Escola SENAI \"Roberto Mange\", na Rua Pastor Cícero Canuto de Lima, 71 - São Bernardo - Campinas - SP." },
  { codigo: "EM335", nome: "Tecnologia Mecânica", semestre: 3, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM240"], ementa: "Normalização. Tolerâncias dimensionais e geométricas. Cadeia de Dimensões. Rugosidade. Metrologia industrial. Princípios de Processos de Fabricação. Planejamento do processo e Sobrematerial. Noções de Controle Estatístico de Processo." },
  { codigo: "EM360", nome: "Termodinâmica I", semestre: 3, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["F 328", "QG101"], ementa: "Conceitos introdutórios e definições. Energia e Primeira Lei da Termodinâmica. Propriedades de uma substância pura. Balanço de energia em volume de controle. Segunda Lei da Termodinâmica. Entropia. Análise exergética." },
  { codigo: "F 259", nome: "Introdução à Física Experimental II", semestre: 3, creditos: 2, tipo: "Obrigatória", departamento: "Física (IFGW)", prerequisitos: ["F 159", "F 328"], ementa: "Produção de gráficos em computador; Linearização de modelos não-lineares; Ajuste linear por software; Coleta de dados a partir da análise de um vídeo; Desvios sistemáticos nos dados; Uso de instrumentos de medição de grandezas eletromagnéticas e termodinâmicas; Medições e curvas de calibração; Coleta automatizada de dados; Testes e comparação de modelos; Trabalho em equipe e ética científica." },
  { codigo: "F 428", nome: "Física Geral IV", semestre: 3, creditos: 4, tipo: "Obrigatória", departamento: "Física (IFGW)", prerequisitos: ["F 328"], ementa: "Ondas Eletromagnéticas, Óptica Geométrica, Interferência, Difração, Teoria da Relatividade, Física Quântica, Modelos Atômicos, Condução de Eletricidade em Sólidos, Física Nuclear, Quarks, Léptons, e o Big-Bang. Obs.: Recomenda-se que seja cursada previamente MA351 ou disciplina equivalente." },
  { codigo: "MA311", nome: "Cálculo III", semestre: 3, creditos: 6, tipo: "Obrigatória", departamento: "Matemática (IMECC)", prerequisitos: ["MA211"], ementa: "Séries numéricas e séries de funções. Equações diferenciais ordinárias. Transformadas de Laplace. Sistemas de equações de primeira ordem. Equações diferenciais parciais e séries de Fourier." },
  { codigo: "MC102", nome: "Algoritmos e Programação de Computadores", semestre: 3, creditos: 6, tipo: "Obrigatória", departamento: "Computação (IC)", prerequisitos: [], ementa: "Conceitos básicos de organização de computadores. Construção de algoritmos e sua representação em pseudocódigo e linguagens de alto nível. Desenvolvimento sistemático e implementação de programas. Estruturação, depuração, testes e documentação de programas. Resolução de problemas." },

  // ---------- 4º SEMESTRE ----------
  { codigo: "EM404", nome: "Dinâmica", semestre: 4, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM306"], ementa: "Estudo vetorial de curvas. Cinemática da partícula. Movimento relativo. Cinemática dos corpos rígidos nos movimentos plano e espacial. Princípios básicos da dinâmica: Leis de Newton, conservação dos momentos linear a angular e conservação de energia. Impacto e atrito. Cinética da partícula. Cinética dos sistemas de partículas. Cinética dos corpos rígidos nos movimentos plano e espacial." },
  { codigo: "EM406", nome: "Resistência dos Materiais I", semestre: 4, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM306", "EM240"], ementa: "Introdução a mecânica dos sólidos. Esforços solicitantes e Equações diferenciais de equilíbrio. Análise de Tensão. Análise de Deformação. Leis constitutivas. Modelos de barra, torção de eixos de seção circular e flexão de vigas." },
  { codigo: "EM460", nome: "Termodinâmica II", semestre: 4, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM360"], ementa: "Ciclos motores a vapor. Ciclos padrão-ar. Ciclos de refrigeração e frigoríficos; bomba de calor. Propriedade de misturas. Pscicrometria. Reações químicas e combustão. Princípios de equilíbrio químico. Relações de Maxwell e propriedades termodinâmicas." },
  { codigo: "EM461", nome: "Mecânica dos Fluidos I", semestre: 4, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM360", "MA311"], ementa: "Introdução e conceitos fundamentais. Lei básica da estática dos fluidos. Leis básicas na forma integral para volume de controle e o Teorema de Transporte de Reynolds. Análise dimensional e semelhança. Escoamento viscoso incompressível interno: perda de carga. Escoamento viscoso incompressível externo: arrasto e sustentação. Máquinas de Fluxo." },
  { codigo: "EM641", nome: "Ensaios dos Materiais", semestre: 4, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM240"], ementa: "Propriedades mecânicas dos materiais. Normas e especificações de ensaios de materiais. Ensaios mecânicos estáticos e dinâmicos. Metalografia. Análise química. Ensaios não destrutivos." },
  { codigo: "MA327", nome: "Álgebra Linear", semestre: 4, creditos: 4, tipo: "Obrigatória", departamento: "Matemática (IMECC)", prerequisitos: ["MA211"], ementa: "Espaços vetoriais reais. Subespaços. Base e dimensão. Transformações lineares e matrizes. Núcleo e imagem. Projeções. Autovalores e autovetores. Produto interno. Matrizes reais especiais. Diagonalização." },
  { codigo: "MS211", nome: "Cálculo Numérico", semestre: 4, creditos: 4, tipo: "Obrigatória", departamento: "Matemática Aplicada (IMECC)", prerequisitos: ["MA311", "MC102"], ementa: "Aritmética de ponto flutuante. Zeros de funções reais. Sistemas lineares. Interpolação polinomial. Integração numérica. Quadrados mínimos lineares. Tratamento numérico de equações diferenciais ordinárias." },
  { codigo: "ELET-4S", nome: "Créditos Eletivos (4º sem.)", semestre: 4, creditos: 2, tipo: "Eletiva", departamento: "Livre escolha", prerequisitos: [], ementa: "Disciplina eletiva de livre escolha do(a) aluno(a) — não possui ementa fixa, pois depende da disciplina escolhida a cada semestre.", eletivaPlaceholder: true },

  // ---------- 5º SEMESTRE ----------
  { codigo: "EM104", nome: "Materiais Poliméricos", semestre: 5, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM240"], ementa: "Ementa oficial ainda não cadastrada automaticamente. Verifique o catálogo de graduação da UNICAMP e adicione manualmente aqui." },
  { codigo: "EM503", nome: "Introdução aos Métodos Numéricos Aplicados à Engenharia", semestre: 5, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["MS211"], ementa: "Introdução aos métodos das diferenças finitas, dos volumes finitos e dos elementos finitos. Uso de aplicativos computacionais na solução de problemas de engenharia mecânica." },
  { codigo: "EM504", nome: "Mecanismos e Dinâmica das Máquinas", semestre: 5, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM404"], ementa: "Graus de liberdade, características e terminologia dos mecanismos articulados planares. Cinemática do engrenamento. Introdução aos camos. Modelagem cinemática e dinâmica por coordenadas generalizadas, Eksergian e introdução aos métodos de energia por Lagrange. Esforços internos." },
  { codigo: "EM506", nome: "Resistência dos Materiais II", semestre: 5, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM406"], ementa: "Tensões de cisalhamento em vigas. Vigas de material composto. Estado de tensão e deformação. Tensões e deformações principais. Carregamentos combinados. Critérios de resistência. Métodos de energia. Flambagem." },
  { codigo: "EM561", nome: "Mecânica dos Fluidos II", semestre: 5, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM461"], ementa: "Forças estáticas exercidas por fluidos sobre superfícies. Conceitos cinemáticos. Introdução à analise diferencial dos escoamentos. Equações de Navier-Stokes. Escoamento incompressível de fluidos não viscosos. Noções de escoamentos em canais abertos. Camada-limite. Introdução ao escoamento compressível." },
  { codigo: "EM570", nome: "Transferência de Calor I", semestre: 5, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM460", "EM461"], ementa: "Introdução à Transferência de Calor.  Condução Unidimensional em Regime Permanente. Condução Bidimensional em Regime Permanente. Condução em regime Transitório: soluções analíticas das formulações concentrada e distribuída e método de solução numérica. Transferência de massa por difusão. Conceitos fundamentais da radiação térmica. Radiação de Superfícies negras e de superfícies opacas difusas e cinzentas. Fator de forma e troca de calor entre superfícies negras e entre superfícies opacas, difusa e cinzentas. Radiação combinada com outros mecanismos de troca de calor e em meios participantes." },
  { codigo: "EM638", nome: "Mecânica e Mecanismos da Fratura", semestre: 5, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM406"], ementa: "Mecanismos de fratura e fadiga. Noções de mecânica da fratura. Fadiga de alto e baixo ciclo. Propagação da trinca por fadiga. Aplicação dos conceitos da mecânica de fratura e fadiga ao projeto estrutural." },
  { codigo: "EM727", nome: "Tecnologia das Ligas Metálicas", semestre: 5, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM240"], ementa: "O sistema ferro-carbono. Decomposição da Austenita e fases metaestáveís. Curvas TTT e CCT. Tratamentos térmicos e termoquímicos. Curvas. Influências dos elementos de liga nos aços. Classificação e seleção dos aços. Produção de Aços. Ferros fundidos: características e aplicações. Metais não ferrosos e suas ligas: tratamentos térmicos, classificação e aplicações." },
  { codigo: "ELET-5S", nome: "Créditos Eletivos (5º sem.)", semestre: 5, creditos: 4, tipo: "Eletiva", departamento: "Livre escolha", prerequisitos: [], ementa: "Disciplina eletiva de livre escolha do(a) aluno(a) — não possui ementa fixa, pois depende da disciplina escolhida a cada semestre.", eletivaPlaceholder: true },

  // ---------- 6º SEMESTRE ----------
  { codigo: "EM535", nome: "Usinagem dos Materiais", semestre: 6, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM335"], ementa: "Normas de usinagem. Mecanismos de formação de cavaco. Forças e potência de corte. Materiais de ferramentas. Desgaste, avarias e vida de ferramentas. Análise das condições econômicas de usinagem. Usinabilidade. Furação. Fresamento. Retificação." },
  { codigo: "EM607", nome: "Vibrações de Sistemas Mecânicos", semestre: 6, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM404", "MA327"], ementa: "Estudo das vibrações mecânicas. Sistemas lineares de um grau de liberdade. Vibrações livres e forçadas. Transformada de Laplace. Transmissibilidade e isolação de vibrações. Sistemas lineares discretos. Frequência natural e modos próprios. Absorvedores de vibração. Introdução aos ensaios dinâmicos." },
  { codigo: "EM665", nome: "Processos Metalúrgicos de Fabricação", semestre: 6, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM727"], ementa: "Introdução à Fundição. Solidificação de Metais e Ligas. Formação de Estruturas Fundidas. Fluxo de material e calor na fundição. Controle da Fusão. Ligas de Fundição. Processos de Fundição: Contínua; Molde Colapsável e Molde Permanente. Projeto de Fundição. Análise Econômica de Fundição. Princípios e Metalurgia da soldagem. Simbologia e normalização em soldagem. Equipamentos e processos de soldagem. Princípios de Metalurgia do Pó. Processos de Metalurgia do Pó e controle de Processos." },
  { codigo: "EM670", nome: "Transferência de Calor II", semestre: 6, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM570"], ementa: "Introdução à troca convectiva de calor e de massa e sua analogia; resfriamento evaporativo e analogia de Reynolds. Troca convectiva de calor e massa em escoamentos forçados externos e internos, nos regimes laminar e turbulento. Convecção natural em superfícies e em cavidades; convecção mista e transferência de massa por convecção natural. Troca de calor com mudança de fase: condensação e ebulição em vaso aberto e em convecção forçada. Trocadores de calor: coeficiente global de troca de calor, métodos DMLT e da efetividade, trocadores de calor compactos." },
  { codigo: "EM733", nome: "Sistemas Produtivos", semestre: 6, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM504"], ementa: "Conceituação da manufatura. Tempos padrões. Classificação dos sistemas de manufatura. Tecnologia de grupo. Produtividade industrial. Planejamento e controle da produção. Teoria das Restrições. MRP I e II. Arranjo físico. Sistema Toyota de Produção." },
  { codigo: "ET017", nome: "Circuitos Elétricos e Eletrotécnica", semestre: 6, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Elétrica (FEEC)", prerequisitos: ["F 428"], ementa: "Revisão de conceitos básicos. Elementos e leis de circuitos elétricos em C.C. e C.A. Circuitos monofásicos e trifásicos. Potência e Energia. Transformadores. Máquinas elétricas rotativas. Instalações elétricas e dispositivos de proteção." },
  { codigo: "ELET-6S", nome: "Créditos Eletivos (6º sem.)", semestre: 6, creditos: 6, tipo: "Eletiva", departamento: "Livre escolha", prerequisitos: [], ementa: "Disciplina eletiva de livre escolha do(a) aluno(a) — não possui ementa fixa, pois depende da disciplina escolhida a cada semestre.", eletivaPlaceholder: true },

  // ---------- 7º SEMESTRE ----------
  { codigo: "EM608", nome: "Elementos de Máquinas", semestre: 7, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM504", "EM506"], ementa: "Dimensionamento de componentes mecânicos à fadiga, fadiga superficial e fratura. Eixos, mancais, engrenagens, molas, junções, embreagens e freios, transmissões flexíveis." },
  { codigo: "EM703", nome: "Instrumentação", semestre: 7, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["ET017"], ementa: "Características estáticas e dinâmicas dos instrumentos e sensores. Análise de dados e incertezas experimentais. Medida e análise de deslocamento, velocidade, aceleração, força, torque, potência mecânica. Problemas na amplificação, transmissão e armazenamento de sinais. Medições de som. Medidas de pressão, vazão e tempreatura. Medidas de propriedades térmicas e de transporte. Introdução ao processamento de sinais, amostragem, filtros digitais, janelamento e espectro de frequência." },
  { codigo: "EM707", nome: "Controle de Sistemas Mecânicos", semestre: 7, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM607", "MS211"], ementa: "Conceitos fundamentais. Critérios de estabilidade. Resposta em frequência. Lugar das raízes. Ações de controle básicas. Noções de modelagem de estado. Aplicações em controle de sistemas mecânicos, hidráulicos e pneumáticos, usando PID/CLP." },
  { codigo: "EM730", nome: "Conformação Mecânica", semestre: 7, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM535"], ementa: "Classificação dos processos de conformação. Metalurgia e mecânica da conformação. Descrição de processos de conformação. Projetos de ferramentas de estampagem e forjamento." },
  { codigo: "EM783", nome: "Laboratório de Calor e Fluidos I", semestre: 7, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM570", "EM561"], ementa: "Conjuntos de experiências de laboratório em termodinâmica básica e aplicada, sistemas fluidomecânicos e fenômenos de transporte. Medição de Pressão, vazão, temperatura e propriedades termofluidodinâmicas. Incertezas de medida." },
  { codigo: "EM833", nome: "Seleção de Materiais", semestre: 7, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM641", "EM727"], ementa: "Critérios de seleção de materiais. Matriz de decisão ponderada. Seleção de materiais(metálicos, poliméricos, cerâmicos e conjugados) para atender às solicitações: resistência mecânica, fadiga, tenacidade, desgaste, altas temperaturas, corrosão. Trabalho prático de seleção de materiais junto à indústria." },
  { codigo: "EM853", nome: "Engenharia Econômica", semestre: 7, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: [], ementa: "Matemática financeira. Custos. Análise de investimentos. Noções de contabilidade." },
  { codigo: "EM884", nome: "Sistemas Fluidotérmicos II", semestre: 7, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM570"], ementa: "Introdução a sistemas fluidotérmicos. Combustíveis e combustão. Geração, distribuição e utilização de vapor. Fornos, aquecedores e incineradores. Sistemas de geração de potência. Turbinas térmicas. Motores de combustão interna. Sistemas de cogeração. Projeto, análise, integração de critérios econômicos, ambientais e otimização de sistemas de geração de potência." },
  { codigo: "ELET-7S", nome: "Créditos Eletivos (7º sem.)", semestre: 7, creditos: 6, tipo: "Eletiva", departamento: "Livre escolha", prerequisitos: [], ementa: "Disciplina eletiva de livre escolha do(a) aluno(a) — não possui ementa fixa, pois depende da disciplina escolhida a cada semestre.", eletivaPlaceholder: true },

  // ---------- 8º SEMESTRE ----------
  { codigo: "BE310", nome: "Ciências do Ambiente", semestre: 8, creditos: 2, tipo: "Obrigatória", departamento: "Biologia (IB)", prerequisitos: [], ementa: "População humana e recursos naturais renováveis e não renováveis. Interação entre o homem e ambientes naturais ou construídos. Ambientes brasileiros terrestres e aquáticos. Análise de ambientes: diagramas energéticos e modelos. O homem como modificador do ambiente. População, energia, clima, ecotoxicologia, extinção, biodiversidade e sustentabilidade. Direito ecológico e política ambiental. Responsabilidade do profissional com relação à sociedade e ao ambiente." },
  { codigo: "CE738", nome: "Economia para Engenharia", semestre: 8, creditos: 4, tipo: "Obrigatória", departamento: "Economia (IE)", prerequisitos: [], ementa: "O processo de produção visto pelas óticas micro e macroeconômicas. Produção e propriedade. Produção como técnica e como processo social. Agregação da produção. Mercados. Papel do governo." },
  { codigo: "EM740", nome: "Laboratório de Engenharia dos Materiais", semestre: 8, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM833"], ementa: "Experiências de laboratório relativas a estrutura, propriedades e transformações de fase de materiais metálicos e não metálicos." },
  { codigo: "EM790", nome: "Engenharia Assistida por Computador", semestre: 8, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM200", "EM503"], ementa: "Conceitos de CAD, CAE e CAM integrados. Sistemas de visualização 2D e 3D. Conceitos de Projeto Mecânico. Modelagem para refinamento, análise e otimização de sistemas mecânicos. Aplicação do método de elementos finitos a problemas estruturais e térmicos. Desenvolvimento de projeto assistido por computador." },
  { codigo: "EM807", nome: "Laboratório de Dinâmica e Vibrações", semestre: 8, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM607"], ementa: "Experimentos com aplicação dos conhecimentos da dinâmica e vibrações." },
  { codigo: "EM984", nome: "Sistemas Fluidotérmicos III", semestre: 8, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM884"], ementa: "Análise sistêmica de instalações de: bombeamento, compressão de gases, recuperação de energia térmica, hidrelétricas, eólicas, refrigeração e conforto térmico. Projeto com a consideração de critérios energéticos, econômicos e ambientais, e otimização dos sistemas objeto de estudo." },
  { codigo: "ELET-8S", nome: "Créditos Eletivos (8º sem.)", semestre: 8, creditos: 4, tipo: "Eletiva", departamento: "Livre escolha", prerequisitos: [], ementa: "Disciplina eletiva de livre escolha do(a) aluno(a) — não possui ementa fixa, pois depende da disciplina escolhida a cada semestre.", eletivaPlaceholder: true },

  // ---------- 9º SEMESTRE ----------
  { codigo: "CE304", nome: "Direito", semestre: 9, creditos: 2, tipo: "Obrigatória", departamento: "Economia/Direito (IE)", prerequisitos: [], ementa: "Fundamento de direito público e privado. Aplicação de normas jurídicas aos fatos econômicos." },
  { codigo: "EM105", nome: "Introdução ao Trabalho de Conclusão de Curso", semestre: 9, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: [], ementa: "Trabalho de caráter teórico e/ou prático, envolvendo conhecimentos adquiridos em diversas disciplinas do curso de Engenharia Mecânica em preparação ao Trabalho de Conclusão de Curso." },
  { codigo: "EM909", nome: "Projeto de Sistemas Mecânicos", semestre: 9, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM608"], ementa: "Metodologia e sistemática do projeto. Métodos de sistematização da criatividade. Concepção a partir de critérios de funcionalidade. QFD e análise do valor. Arquitetura mecânica. Metodologias Design for X: Segurança, Manufatura, Confiabilidade. Otimização. Documentação de projeto. Projeto detalhado. Prototipagem e maquetagem." },
  { codigo: "EM928", nome: "Projeto do Processo", semestre: 9, creditos: 4, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM733"], ementa: "Projeto de Sistemas de Manufatura. Geração da peça em bruto e seleção de processos. Sequenciamento Completo de Operações e Determinação de Operações Intermediárias. Detalhamento de Operações. Seleção dos Equipamentos de Produção e de Dispositivos Especiais. Montagem. Projeto da Instalação Fabril." },
  { codigo: "ELET-9S", nome: "Créditos Eletivos (9º sem.)", semestre: 9, creditos: 2, tipo: "Eletiva", departamento: "Livre escolha", prerequisitos: [], ementa: "Disciplina eletiva de livre escolha do(a) aluno(a) — não possui ementa fixa, pois depende da disciplina escolhida a cada semestre.", eletivaPlaceholder: true },

  // ---------- 10º SEMESTRE ----------
  { codigo: "EM107", nome: "Trabalho de Conclusão de Curso", semestre: 10, creditos: 2, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: ["EM105"], ementa: "Trabalho de caráter teórico e/ou prático, envolvendo conhecimentos adquiridos em diversas disciplinas do curso de Engenharia Mecânica. A monografia padronizada será analisada por uma banca contendo ao menos dois avaliadores além do orientador." },
  { codigo: "EM916", nome: "Estágio Supervisionado", semestre: 10, creditos: 12, tipo: "Obrigatória", departamento: "Engenharia Mecânica (FEM)", prerequisitos: [], ementa: "Acompanhamento de projetos. Montagens e execuções de equipamentos e sistemas em Engenharia Mecânica junto a um órgão credenciado pelo departamento. O estágio é orientado bilateralmente e conclui com a apresentação de um relatório." },

];

// Total de créditos do currículo (usado no dashboard)
const TOTAL_CREDITOS_CURSO = DISCIPLINAS.reduce((soma, d) => soma + d.creditos, 0);
const TOTAL_DISCIPLINAS_CURSO = DISCIPLINAS.length;
const NOME_CURSO = "Engenharia Mecânica";
const INSTITUICAO = "UNICAMP";
const NUM_SEMESTRES = 10;